MuR.Crafting = MuR.Crafting or {}
MuR.Crafting.Recipes = {}
MuR.Crafting.Ingredients = {}

MuR.Crafting.Ingredients = {
	["pseudoephedrine"] = {
		name = "Псевдоэфедрин",
		formula = "C₁₀H₁₅NO",
		latin = "Pseudoephedrinum",
		model = "models/props_lab/jar01a.mdl",
		description = "Таблетки от простуды",
		lootChance = 8,
	},
	["lithium"] = {
		name = "Литий",
		formula = "Li",
		latin = "Lithium",
		model = "models/props_c17/canister02a.mdl",
		description = "Полоски из батареек",
		lootChance = 6,
	},
	["anhydrous_ammonia"] = {
		name = "Безводный аммиак",
		formula = "NH₃",
		latin = "Ammonia anhydrica",
		model = "models/props_lab/jar01b.mdl",
		description = "Компонент удобрений",
		lootChance = 5,
	},
	["red_phosphorus"] = {
		name = "Красный фосфор",
		formula = "P",
		latin = "Phosphorus ruber",
		model = "models/props_lab/jar01b.mdl",
		description = "Материал спичечных коробков",
		lootChance = 4,
	},
	["iodine"] = {
		name = "Йод",
		formula = "I₂",
		latin = "Iodum",
		model = "models/props_lab/jar01a.mdl",
		description = "Медицинский антисептик",
		lootChance = 7,
	},
	["acetone"] = {
		name = "Ацетон",
		formula = "C₃H₆O",
		latin = "Acetonum",
		model = "models/props_junk/garbage_metalcan001a.mdl",
		description = "Жидкость для снятия лака",
		lootChance = 10,
	},
	["hydrochloric_acid"] = {
		name = "Соляная кислота",
		formula = "HCl",
		latin = "Acidum hydrochloricum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Средство для чистки труб",
		lootChance = 8,
	},
	["sodium_hydroxide"] = {
		name = "Гидроксид натрия",
		formula = "NaOH",
		latin = "Natrii hydroxidum",
		model = "models/props_lab/jar01a.mdl",
		description = "Едкий натр для производства мыла",
		lootChance = 9,
	},
	["sulfuric_acid"] = {
		name = "Серная кислота",
		formula = "H₂SO₄",
		latin = "Acidum sulfuricum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Кислота из автомобильного аккумулятора",
		lootChance = 7,
	},
	["acetic_anhydride"] = {
		name = "Уксусный ангидрид",
		formula = "C₄H₆O₃",
		latin = "Acidum aceticum anhydricum",
		model = "models/props_lab/jar01b.mdl",
		description = "Химический реагент",
		lootChance = 3,
	},
	["morphine_base"] = {
		name = "База морфина",
		formula = "C₁₇H₁₉NO₃",
		latin = "Morphinum",
		model = "models/props_lab/jar01a.mdl",
		description = "Экстракт из опиума",
		lootChance = 2,
	},
	["ergot_fungus"] = {
		name = "Спорынья",
		formula = "Claviceps",
		latin = "Secale cornutum",
		model = "models/props_lab/jar01a.mdl",
		description = "Паразит зерновых культур",
		lootChance = 3,
	},
	["lysergic_acid"] = {
		name = "Лизергиновая кислота",
		formula = "C₁₆H₁₆N₂O₂",
		latin = "Acidum lysergicum",
		model = "models/props_lab/jar01b.mdl",
		description = "Производное эрготамина",
		lootChance = 2,
	},
	["diethylamine"] = {
		name = "Диэтиламин",
		formula = "C₄H₁₁N",
		latin = "Diethylaminum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Промышленный растворитель",
		lootChance = 4,
	},
	["sodium_cyanide"] = {
		name = "Цианид натрия",
		formula = "NaCN",
		latin = "Natrii cyanidum",
		model = "models/props_lab/jar01a.mdl",
		description = "Химикат для добычи руды",
		lootChance = 3,
	},
	["potassium_chlorate"] = {
		name = "Хлорат калия",
		formula = "KClO₃",
		latin = "Kalii chloras",
		model = "models/props_lab/jar01a.mdl",
		description = "Окислитель",
		lootChance = 5,
	},
	["aluminum_powder"] = {
		name = "Алюминиевый порошок",
		formula = "Al",
		latin = "Aluminium pulvis",
		model = "models/props_lab/jar01a.mdl",
		description = "Мелкий металлический порошок",
		lootChance = 6,
	},
	["activated_charcoal"] = {
		name = "Активированный уголь",
		formula = "C",
		latin = "Carbo activatus",
		model = "models/props_lab/jar01a.mdl",
		description = "Фильтрующий материал",
		lootChance = 8,
	},
	["ethanol"] = {
		name = "Этанол",
		formula = "C₂H₅OH",
		latin = "Aethanolum",
		model = "models/props_junk/garbage_glassbottle001a.mdl",
		description = "Зерновой спирт",
		lootChance = 12,
	},
	["ether"] = {
		name = "Эфир",
		formula = "C₄H₁₀O",
		latin = "Aether",
		model = "models/props_junk/garbage_glassbottle002a.mdl",
		description = "Летучий растворитель",
		lootChance = 5,
	},
	["potassium_nitrate"] = {
		name = "Нитрат калия",
		formula = "KNO₃",
		latin = "Kalii nitras",
		model = "models/props_lab/jar01a.mdl",
		description = "Селитра, удобрение",
		lootChance = 7,
	},
	["ammonium_nitrate"] = {
		name = "Нитрат аммония",
		formula = "NH₄NO₃",
		latin = "Ammonii nitras",
		model = "models/props_lab/jar01b.mdl",
		description = "Аммиачная селитра",
		lootChance = 6,
	},
	["nitric_acid"] = {
		name = "Азотная кислота",
		formula = "HNO₃",
		latin = "Acidum nitricum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Концентрированная кислота",
		lootChance = 4,
	},
	["glycerin"] = {
		name = "Глицерин",
		formula = "C₃H₈O₃",
		latin = "Glycerinum",
		model = "models/props_junk/garbage_glassbottle001a.mdl",
		description = "Медицинский глицерол",
		lootChance = 8,
	},
	["methanol"] = {
		name = "Метанол",
		formula = "CH₃OH",
		latin = "Methanolum",
		model = "models/props_junk/garbage_glassbottle002a.mdl",
		description = "Технический спирт",
		lootChance = 9,
	},
	["hydrogen_peroxide"] = {
		name = "Перекись водорода",
		formula = "H₂O₂",
		latin = "Hydrogenium peroxydatum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Антисептический раствор",
		lootChance = 10,
	},
	["phenol"] = {
		name = "Фенол",
		formula = "C₆H₅OH",
		latin = "Phenolum",
		model = "models/props_lab/jar01a.mdl",
		description = "Карболовая кислота",
		lootChance = 5,
	},
	["benzene"] = {
		name = "Бензол",
		formula = "C₆H₆",
		latin = "Benzenum",
		model = "models/props_junk/garbage_metalcan001a.mdl",
		description = "Органический растворитель",
		lootChance = 4,
	},
	["toluene"] = {
		name = "Толуол",
		formula = "C₇H₈",
		latin = "Toluenum",
		model = "models/props_junk/garbage_metalcan001a.mdl",
		description = "Растворитель красок",
		lootChance = 6,
	},
	["formaldehyde"] = {
		name = "Формальдегид",
		formula = "CH₂O",
		latin = "Formaldehydum",
		model = "models/props_junk/garbage_glassbottle001a.mdl",
		description = "Консервирующий раствор",
		lootChance = 5,
	},
	["chlorine"] = {
		name = "Хлор",
		formula = "Cl₂",
		latin = "Chlorum",
		model = "models/props_c17/canister02a.mdl",
		description = "Газообразный галоген",
		lootChance = 3,
	},
	["phosphoric_acid"] = {
		name = "Фосфорная кислота",
		formula = "H₃PO₄",
		latin = "Acidum phosphoricum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Средство от ржавчины",
		lootChance = 7,
	},
	["calcium_carbide"] = {
		name = "Карбид кальция",
		formula = "CaC₂",
		latin = "Calcii carbidum",
		model = "models/props_lab/jar01a.mdl",
		description = "Газогенерирующее вещество",
		lootChance = 4,
	},
	["sodium_chlorate"] = {
		name = "Хлорат натрия",
		formula = "NaClO₃",
		latin = "Natrii chloras",
		model = "models/props_lab/jar01b.mdl",
		description = "Гербицид",
		lootChance = 5,
	},
	["picric_acid"] = {
		name = "Пикриновая кислота",
		formula = "C₆H₃N₃O₇",
		latin = "Acidum picricum",
		model = "models/props_lab/jar01a.mdl",
		description = "Тринитрофенол",
		lootChance = 2,
	},
	["mercury"] = {
		name = "Ртуть",
		formula = "Hg",
		latin = "Hydrargyrum",
		model = "models/props_lab/jar01b.mdl",
		description = "Жидкий металл из термометра",
		lootChance = 3,
	},
	["arsenic_trioxide"] = {
		name = "Триоксид мышьяка",
		formula = "As₂O₃",
		latin = "Arsenicum album",
		model = "models/props_lab/jar01a.mdl",
		description = "Крысиный яд",
		lootChance = 2,
	},
	["potassium_permanganate"] = {
		name = "Перманганат калия",
		formula = "KMnO₄",
		latin = "Kalii permanganas",
		model = "models/props_lab/jar01a.mdl",
		description = "Марганцовка",
		lootChance = 8,
	},
	["ammonia_solution"] = {
		name = "Раствор аммиака",
		formula = "NH₄OH",
		latin = "Solutio ammonii",
		model = "models/props_junk/garbage_glassbottle002a.mdl",
		description = "Нашатырный спирт",
		lootChance = 9,
	},
	["sodium_bicarbonate"] = {
		name = "Бикарбонат натрия",
		formula = "NaHCO₃",
		latin = "Natrii hydrocarbonas",
		model = "models/props_lab/jar01a.mdl",
		description = "Пищевая сода",
		lootChance = 11,
	},
	["magnesium_powder"] = {
		name = "Магниевый порошок",
		formula = "Mg",
		latin = "Magnesium pulvis",
		model = "models/props_lab/jar01b.mdl",
		description = "Легковоспламеняющийся металл",
		lootChance = 5,
	},
	["zinc_powder"] = {
		name = "Цинковый порошок",
		formula = "Zn",
		latin = "Zincum pulvis",
		model = "models/props_lab/jar01a.mdl",
		description = "Металлический восстановитель",
		lootChance = 6,
	},
	["copper_sulfate"] = {
		name = "Сульфат меди",
		formula = "CuSO₄",
		latin = "Cupri sulfas",
		model = "models/props_lab/jar01a.mdl",
		description = "Медный купорос",
		lootChance = 7,
	},
	["iron_oxide"] = {
		name = "Оксид железа",
		formula = "Fe₂O₃",
		latin = "Ferri oxidum",
		model = "models/props_lab/jar01b.mdl",
		description = "Ржавчина, красный пигмент",
		lootChance = 8,
	},
	["sulfur"] = {
		name = "Сера",
		formula = "S",
		latin = "Sulfur",
		model = "models/props_lab/jar01a.mdl",
		description = "Желтый горючий элемент",
		lootChance = 6,
	},
	["potassium_iodide"] = {
		name = "Йодид калия",
		formula = "KI",
		latin = "Kalii iodidum",
		model = "models/props_lab/jar01a.mdl",
		description = "Йодная соль",
		lootChance = 5,
	},
	["silver_nitrate"] = {
		name = "Нитрат серебра",
		formula = "AgNO₃",
		latin = "Argenti nitras",
		model = "models/props_lab/jar01b.mdl",
		description = "Ляпис",
		lootChance = 3,
	},
	["barium_chloride"] = {
		name = "Хлорид бария",
		formula = "BaCl₂",
		latin = "Barii chloridum",
		model = "models/props_lab/jar01a.mdl",
		description = "Реактив для осаждения",
		lootChance = 4,
	},
	["lead_acetate"] = {
		name = "Ацетат свинца",
		formula = "Pb(C₂H₃O₂)₂",
		latin = "Plumbi acetas",
		model = "models/props_lab/jar01b.mdl",
		description = "Свинцовый сахар",
		lootChance = 3,
	},
	["oxalic_acid"] = {
		name = "Щавелевая кислота",
		formula = "C₂H₂O₄",
		latin = "Acidum oxalicum",
		model = "models/props_lab/jar01a.mdl",
		description = "Чистящее средство",
		lootChance = 6,
	},
	["citric_acid"] = {
		name = "Лимонная кислота",
		formula = "C₆H₈O₇",
		latin = "Acidum citricum",
		model = "models/props_lab/jar01a.mdl",
		description = "Пищевая добавка",
		lootChance = 10,
	},
	["borax"] = {
		name = "Бура",
		formula = "Na₂B₄O₇",
		latin = "Borax",
		model = "models/props_lab/jar01b.mdl",
		description = "Тетраборат натрия",
		lootChance = 7,
	},
	["calcium_chloride"] = {
		name = "Хлорид кальция",
		formula = "CaCl₂",
		latin = "Calcii chloridum",
		model = "models/props_lab/jar01a.mdl",
		description = "Противогололедный реагент",
		lootChance = 8,
	},
	["sodium_thiosulfate"] = {
		name = "Тиосульфат натрия",
		formula = "Na₂S₂O₃",
		latin = "Natrii thiosulfas",
		model = "models/props_lab/jar01b.mdl",
		description = "Гипосульфит",
		lootChance = 5,
	},
	["ephedrine"] = {
		name = "Эфедрин",
		formula = "C₁₀H₁₅NO",
		latin = "Ephedrinum",
		model = "models/props_lab/jar01a.mdl",
		description = "Бронхорасширяющее средство",
		lootChance = 3,
	},
	["codeine"] = {
		name = "Кодеин",
		formula = "C₁₈H₂₁NO₃",
		latin = "Codeinum",
		model = "models/props_lab/jar01b.mdl",
		description = "Противокашлевой препарат",
		lootChance = 4,
	},
	["thionyl_chloride"] = {
		name = "Тионилхлорид",
		formula = "SOCl₂",
		latin = "Thionyl chloridum",
		model = "models/props_junk/garbage_plasticbottle003a.mdl",
		description = "Хлорирующий агент",
		lootChance = 2,
	},
	["phosphorus_pentoxide"] = {
		name = "Пентоксид фосфора",
		formula = "P₂O₅",
		latin = "Phosphori pentoxidum",
		model = "models/props_lab/jar01a.mdl",
		description = "Осушающий агент",
		lootChance = 3,
	},
	["sodium_azide"] = {
		name = "Азид натрия",
		formula = "NaN₃",
		latin = "Natrii azidum",
		model = "models/props_lab/jar01b.mdl",
		description = "Взрывчатое вещество из подушек безопасности",
		lootChance = 2,
	},
	["phosgene_precursor"] = {
		name = "Прекурсор фосгена",
		formula = "CCl₄",
		latin = "Carboneum tetrachloride",
		model = "models/props_junk/garbage_metalcan001a.mdl",
		description = "Четыреххлористый углерод",
		lootChance = 2,
	},
	["potassium_chloride"] = {
		name = "Хлорид калия",
		formula = "KCl",
		latin = "Kalii chloridum",
		model = "models/props_lab/jar01a.mdl",
		description = "Минеральная соль, удобрение",
		lootChance = 8,
	},
}

MuR.Crafting.Recipes = {
	["mur_meth"] = {
		name = "Метамфетамин",
		formula = "C₁₀H₁₅N",
		latin = "Methamphetaminum",
		result = "mur_meth",
		ingredients = {
			["pseudoephedrine"] = 3,
			["lithium"] = 1,
			["anhydrous_ammonia"] = 2,
			["red_phosphorus"] = 1,
			["iodine"] = 1,
			["hydrochloric_acid"] = 1,
		},
		craftTime = 60,
		difficulty = 0.85,
		category = "stimulants",
		description = "Синтез через восстановление псевдоэфедрина литием и аммиаком",
	},
	["mur_heroin_craft"] = {
		name = "Героин",
		formula = "C₂₁H₂₃NO₅",
		latin = "Diacetylmorphinum",
		result = "mur_heroin",
		ingredients = {
			["morphine_base"] = 2,
			["acetic_anhydride"] = 2,
			["sodium_hydroxide"] = 1,
			["activated_charcoal"] = 1,
		},
		craftTime = 45,
		difficulty = 0.75,
		category = "opioids",
		description = "Ацетилирование морфина до диацетилморфина",
	},
	["mur_lsd"] = {
		name = "ЛСД",
		formula = "C₂₀H₂₅N₃O",
		latin = "Lysergidum",
		result = "mur_lsd",
		ingredients = {
			["ergot_fungus"] = 2,
			["lysergic_acid"] = 1,
			["diethylamine"] = 2,
			["ethanol"] = 1,
		},
		craftTime = 90,
		difficulty = 0.95,
		category = "hallucinogens",
		description = "Синтез диэтиламида лизергиновой кислоты из алкалоидов спорыньи",
	},
	["mur_cocaine_base"] = {
		name = "База кокаина",
		formula = "C₁₇H₂₁NO₄",
		latin = "Cocainum",
		result = "mur_cocaine",
		ingredients = {
			["acetone"] = 2,
			["hydrochloric_acid"] = 2,
			["sodium_hydroxide"] = 1,
			["ether"] = 1,
		},
		craftTime = 50,
		difficulty = 0.80,
		category = "stimulants",
		description = "Процесс экстракции и базового преобразования",
	},
	["mur_chloroform"] = {
		name = "Хлороформ",
		formula = "CHCl₃",
		latin = "Chloroformium",
		result = "mur_chloroform",
		ingredients = {
			["acetone"] = 3,
			["sodium_hydroxide"] = 2,
			["ethanol"] = 1,
		},
		craftTime = 30,
		difficulty = 0.65,
		category = "anesthetics",
		description = "Галоформная реакция с ацетоном и отбеливателем",
	},
	["mur_ricin"] = {
		name = "Рицин",
		formula = "C₃₅H₅₂N₄O₁₀",
		latin = "Ricinum",
		result = "mur_ricin",
		ingredients = {
			["sodium_hydroxide"] = 2,
			["acetone"] = 2,
			["hydrochloric_acid"] = 1,
		},
		craftTime = 40,
		difficulty = 0.70,
		category = "toxins",
		description = "Экстракция из касторовых бобов через химическую изоляцию",
	},
	["mur_thermite"] = {
		name = "Термит",
		formula = "Al + Fe₂O₃",
		latin = "Thermitum",
		result = "mur_thermite",
		ingredients = {
			["aluminum_powder"] = 3,
			["potassium_chlorate"] = 2,
		},
		craftTime = 20,
		difficulty = 0.50,
		category = "incendiaries",
		description = "Смесь металлического порошка и окислителя для экзотермической реакции",
	},
	["mur_nitrogen_mustard"] = {
		name = "Азотистый иприт",
		formula = "C₄H₉Cl₂N",
		latin = "Yperitum nitrosum",
		result = "mur_nitrogen_mustard",
		ingredients = {
			["hydrochloric_acid"] = 3,
			["ethanol"] = 2,
			["sodium_hydroxide"] = 2,
		},
		craftTime = 55,
		difficulty = 0.88,
		category = "chemical_weapons",
		description = "Синтез везиканта через хлорирование",
	},
	["mur_strychnine"] = {
		name = "Стрихнин",
		formula = "C₂₁H₂₂N₂O₂",
		latin = "Strychninum",
		result = "mur_strychnine",
		ingredients = {
			["sulfuric_acid"] = 2,
			["ethanol"] = 2,
			["activated_charcoal"] = 1,
		},
		craftTime = 35,
		difficulty = 0.72,
		category = "toxins",
		description = "Экстракция алкалоида из семян чилибухи",
	},
	["mur_antidote"] = {
		name = "Универсальное противоядие",
		formula = "C + NaOH",
		latin = "Antidotum universale",
		result = "mur_antidote",
		ingredients = {
			["activated_charcoal"] = 2,
			["sodium_hydroxide"] = 1,
			["ethanol"] = 1,
		},
		craftTime = 25,
		difficulty = 0.40,
		category = "medical",
		description = "Общий состав для лечения отравлений",
	},
	["mur_nitroglycerin"] = {
		name = "Нитроглицерин",
		formula = "C₃H₅N₃O₉",
		latin = "Nitroglycerinum",
		result = "mur_nitroglycerin",
		ingredients = {
			["glycerin"] = 3,
			["nitric_acid"] = 4,
			["sulfuric_acid"] = 2,
		},
		craftTime = 180,
		difficulty = 0.90,
		category = "explosives",
		description = "Нестабильное взрывчатое вещество с сердечными эффектами",
	},
	["mur_picric_explosive"] = {
		name = "Мелинит",
		formula = "C₆H₃N₃O₇",
		latin = "Acidum picricum explosivum",
		result = "mur_picric_explosive",
		ingredients = {
			["picric_acid"] = 5,
			["potassium_nitrate"] = 2,
			["sulfur"] = 1,
		},
		craftTime = 150,
		difficulty = 0.85,
		category = "explosives",
		description = "Мощное бризантное взрывчатое вещество",
	},
	["mur_mercury_fulminate"] = {
		name = "Гремучая ртуть",
		formula = "Hg(CNO)₂",
		latin = "Mercurius fulminans",
		result = "mur_mercury_fulminate",
		ingredients = {
			["mercury"] = 3,
			["nitric_acid"] = 3,
			["ethanol"] = 2,
		},
		craftTime = 120,
		difficulty = 0.80,
		category = "incendiaries",
		description = "Первичное инициирующее взрывчатое вещество",
	},
	["mur_phosgene"] = {
		name = "Фосген",
		formula = "COCl₂",
		latin = "Phosgene",
		result = "mur_phosgene",
		ingredients = {
			["phosgene_precursor"] = 3,
			["chlorine"] = 4,
			["activated_charcoal"] = 1,
		},
		craftTime = 90,
		difficulty = 0.75,
		category = "chemical_weapons",
		description = "Удушающий боевой газ",
	},
	["mur_sarin_like"] = {
		name = "Фосфорорганическое соединение",
		formula = "C₄H₁₀FO₂P",
		latin = "Organophosphorus compound",
		result = "mur_sarin_like",
		ingredients = {
			["phosphoric_acid"] = 5,
			["isopropanol"] = 3,
			["thionyl_chloride"] = 3,
			["sodium_fluoride"] = 2,
		},
		craftTime = 240,
		difficulty = 0.95,
		category = "chemical_weapons",
		description = "Нервно-паралитический агент",
	},
	["mur_arsenic_poison"] = {
		name = "Мышьяковый яд",
		formula = "As₂O₃",
		latin = "Arsenicum album veneni",
		result = "mur_arsenic_poison",
		ingredients = {
			["arsenic_trioxide"] = 4,
			["citric_acid"] = 2,
			["sodium_bicarbonate"] = 1,
		},
		craftTime = 60,
		difficulty = 0.55,
		category = "toxins",
		description = "Классический медленнодействующий яд",
	},
	["mur_lead_poison"] = {
		name = "Свинцовый раствор",
		formula = "Pb(C₂H₃O₂)₂",
		latin = "Plumbi acetas solutio",
		result = "mur_lead_poison",
		ingredients = {
			["lead_acetate"] = 3,
			["citric_acid"] = 2,
			["water"] = 1,
		},
		craftTime = 45,
		difficulty = 0.45,
		category = "toxins",
		description = "Вызывает свинцовое отравление",
	},
	["mur_cyanide_gas"] = {
		name = "Синильная кислота",
		formula = "HCN",
		latin = "Acidum hydrocyanicum",
		result = "mur_cyanide_gas",
		ingredients = {
			["sodium_cyanide"] = 3,
			["sulfuric_acid"] = 2,
			["water"] = 1,
		},
		craftTime = 75,
		difficulty = 0.70,
		category = "chemical_weapons",
		description = "Смертельный газ, блокирующий дыхание клеток",
	},
	["mur_chlorine_gas"] = {
		name = "Газообразный хлор",
		formula = "Cl₂",
		latin = "Chlorum gaseum",
		result = "mur_chlorine_gas",
		ingredients = {
			["chlorine"] = 4,
			["hydrochloric_acid"] = 2,
			["potassium_permanganate"] = 1,
		},
		craftTime = 60,
		difficulty = 0.60,
		category = "chemical_weapons",
		description = "Удушающий газ желто-зеленого цвета",
	},
	["mur_ketamine_craft"] = {
		name = "Кетамин",
		formula = "C₁₃H₁₆ClNO",
		latin = "Ketaminum",
		result = "mur_ketamine_craft",
		ingredients = {
			["phenol"] = 3,
			["methylamine"] = 2,
			["hydrochloric_acid"] = 2,
			["ether"] = 1,
		},
		craftTime = 120,
		difficulty = 0.75,
		category = "anesthetics",
		description = "Диссоциативный анестетик с галлюциногенными эффектами",
	},
	["mur_ghb"] = {
		name = "ГОМК",
		formula = "C₄H₈O₃",
		latin = "Acidum gamma-hydroxybutyricum",
		result = "mur_ghb",
		ingredients = {
			["gamma_butyrolactone"] = 3,
			["sodium_hydroxide"] = 2,
			["water"] = 1,
		},
		craftTime = 90,
		difficulty = 0.65,
		category = "sedatives",
		description = "Гамма-гидроксимасляная кислота, депрессант ЦНС",
	},
	["mur_dmso_poison"] = {
		name = "ДМСО с ядом",
		formula = "C₂H₆OS + токсин",
		latin = "Dimethyl sulfoxide toxicum",
		result = "mur_dmso_poison",
		ingredients = {
			["dimethyl_sulfoxide"] = 2,
			["ricin"] = 1,
			["mercury"] = 1,
		},
		craftTime = 60,
		difficulty = 0.68,
		category = "toxins",
		description = "Транспортирует яд через кожу",
	},
	["mur_ammonia_bomb"] = {
		name = "Аммиачная бомба",
		formula = "NH₃",
		latin = "Ammonia explosiva",
		result = "murwep_ammonia_bomb",
		ingredients = {
			["ammonia_solution"] = 4,
			["aluminum_powder"] = 2,
			["water"] = 1,
		},
		craftTime = 45,
		difficulty = 0.55,
		category = "incendiaries",
		description = "Выделяет удушающий газ и брызги",
	},
	["mur_white_phosphorus"] = {
		name = "Белый фосфор",
		formula = "P₄",
		latin = "Phosphorus albus",
		result = "murwep_white_phosphorus",
		ingredients = {
			["phosphoric_acid"] = 4,
			["aluminum_powder"] = 3,
			["magnesium_powder"] = 2,
		},
		craftTime = 150,
		difficulty = 0.82,
		category = "incendiaries",
		description = "Самовоспламеняющееся зажигательное вещество",
	},
	["mur_silver_explosive"] = {
		name = "Азид серебра",
		formula = "AgN₃",
		latin = "Argenti azidum",
		result = "murwep_silver_explosive",
		ingredients = {
			["silver_nitrate"] = 3,
			["sodium_azide"] = 3,
			["water"] = 1,
		},
		craftTime = 90,
		difficulty = 0.78,
		category = "incendiaries",
		description = "Крайне чувствительное инициирующее ВВ",
	},
	["mur_barium_poison"] = {
		name = "Барий хлорид",
		formula = "BaCl₂",
		latin = "Barii chloridum concentrate",
		result = "mur_barium_poison",
		ingredients = {
			["barium_chloride"] = 4,
			["citric_acid"] = 2,
		},
		craftTime = 30,
		difficulty = 0.40,
		category = "toxins",
		description = "Вызывает паралич мышц и остановку сердца",
	},
	["mur_oxalic_poison"] = {
		name = "Концентрат щавелевой кислоты",
		formula = "C₂H₂O₄",
		latin = "Acidum oxalicum concentrate",
		result = "mur_oxalic_poison",
		ingredients = {
			["oxalic_acid"] = 5,
			["sulfuric_acid"] = 2,
		},
		craftTime = 40,
		difficulty = 0.45,
		category = "toxins",
		description = "Повреждает почки и связывает кальций",
	},
	["mur_sodium_azide_bomb"] = {
		name = "Азидная бомба",
		formula = "NaN₃",
		latin = "Natrii azidum explosivum",
		result = "murwep_sodium_azide_bomb",
		ingredients = {
			["sodium_azide"] = 4,
			["citric_acid"] = 2,
			["water"] = 1,
		},
		craftTime = 60,
		difficulty = 0.72,
		category = "incendiaries",
		description = "Выделяет токсичный газ при реакции",
	},
	["mur_flash_powder"] = {
		name = "Вспышечный порошок",
		formula = "Mg + KClO₃",
		latin = "Pulvis fulgurans",
		result = "murwep_flash_powder",
		ingredients = {
			["magnesium_powder"] = 3,
			["potassium_chlorate"] = 3,
			["sulfur"] = 1,
		},
		craftTime = 45,
		difficulty = 0.58,
		category = "incendiaries",
		description = "Яркая вспышка и оглушение",
	},
	["mur_ephedrine_extract"] = {
		name = "Экстракт эфедрина",
		formula = "C₁₀H₁₅NO",
		latin = "Ephedrinum extractum",
		result = "mur_ephedrine_extract",
		ingredients = {
			["ephedrine"] = 4,
			["ethanol"] = 2,
			["sodium_hydroxide"] = 1,
		},
		craftTime = 50,
		difficulty = 0.62,
		category = "stimulants",
		description = "Концентрированный стимулятор",
	},
	["mur_loot_adrenaline"] = {
		name = "Адреналин",
		formula = "C₉H₁₃NO₃",
		latin = "Adrenalinum",
		result = "mur_loot_adrenaline",
		ingredients = {
			["ephedrine"] = 3,
			["phenol"] = 2,
			["hydrogen_peroxide"] = 2,
			["sodium_hydroxide"] = 1,
		},
		craftTime = 70,
		difficulty = 0.68,
		category = "medical",
		description = "Гормон надпочечников, мощный стимулятор сердечно-сосудистой системы",
	},
	["mur_cyanide"] = {
		name = "Цианид калия",
		formula = "KCN",
		latin = "Kalii cyanidum",
		result = "mur_cyanide",
		ingredients = {
			["sodium_cyanide"] = 3,
			["potassium_chloride"] = 2,
			["citric_acid"] = 1,
		},
		craftTime = 40,
		difficulty = 0.58,
		category = "toxins",
		description = "Смертельный яд, блокирует клеточное дыхание",
	},
	["mur_tranq"] = {
		name = "Мидазолам",
		formula = "C₁₈H₁₃ClFN₃",
		latin = "Midazolamum",
		result = "mur_tranq",
		ingredients = {
			["phenol"] = 3,
			["chlorine"] = 2,
			["ammonia_solution"] = 2,
			["ethanol"] = 1,
		},
		craftTime = 80,
		difficulty = 0.72,
		category = "sedatives",
		description = "Мидазолам - бензодиазепин короткого действия, сильный седативный эффект",
	},
	["mur_bredogen"] = {
		name = "Фенциклидин",
		formula = "C₁₇H₂₅N",
		latin = "Phencyclidinum",
		result = "mur_bredogen",
		ingredients = {
			["morphine_base"] = 2,
			["phenol"] = 2,
			["ammonia_solution"] = 2,
			["sulfuric_acid"] = 1,
		},
		craftTime = 90,
		difficulty = 0.78,
		category = "hallucinogens",
		description = "Фенциклидин (PCP) - диссоциативный анестетик, вызывает делирий и галлюцинации",
	},
}

function MuR.Crafting:GetRecipe(id)
	return self.Recipes[id]
end

function MuR.Crafting:GetIngredient(id)
	return self.Ingredients[id]
end

function MuR.Crafting:CanCraft(ply, recipeID)
	local recipe = self:GetRecipe(recipeID)
	if !recipe then return false end

	if !ply.CraftingInventory then
		ply.CraftingInventory = {}
	end

	for ingredient, amount in pairs(recipe.ingredients) do
		local has = ply.CraftingInventory[ingredient] or 0
		if has < amount then
			return false
		end
	end

	return true
end

function MuR.Crafting:GetRecipesByCategory(category)
	local recipes = {}
	for id, recipe in pairs(self.Recipes) do
		if recipe.category == category then
			table.insert(recipes, {id = id, data = recipe})
		end
	end
	return recipes
end

function MuR.Crafting:GetAllCategories()
	local categories = {}
	for _, recipe in pairs(self.Recipes) do
		if !table.HasValue(categories, recipe.category) then
			table.insert(categories, recipe.category)
		end
	end
	return categories
end
